{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNLHTqKQ2fsU377zsVsHMTX",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/gundalarakesh262-cpu/nifty100-financial-intelligence/blob/main/src/analytics/peer_comparison_report.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 349
        },
        "id": "oX5cRztLWv7H",
        "outputId": "ed210c75-af4f-483c-f0c0-f01f59468cce"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "NameError",
          "evalue": "name '__file__' is not defined",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipykernel_1418/2029669501.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[0;31m# Path Setup\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0;31m# ---------------------------------------------------------\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 14\u001b[0;31m \u001b[0mROOT_DIR\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mPath\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m__file__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresolve\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparents\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     15\u001b[0m \u001b[0mDATA_DIR\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mROOT_DIR\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;34m\"data\"\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;34m\"processed\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     16\u001b[0m \u001b[0mRAW_DIR\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mROOT_DIR\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;34m\"data\"\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;34m\"raw\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mNameError\u001b[0m: name '__file__' is not defined"
          ]
        }
      ],
      "source": [
        "from pathlib import Path\n",
        "import re\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "\n",
        "from openpyxl import load_workbook\n",
        "from openpyxl.styles import PatternFill, Font, Alignment, Border, Side\n",
        "from openpyxl.utils import get_column_letter\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Path Setup\n",
        "# ---------------------------------------------------------\n",
        "ROOT_DIR = Path(__file__).resolve().parents[2]\n",
        "DATA_DIR = ROOT_DIR / \"data\" / \"processed\"\n",
        "RAW_DIR = ROOT_DIR / \"data\" / \"raw\"\n",
        "OUTPUT_DIR = ROOT_DIR / \"output\"\n",
        "\n",
        "OUTPUT_DIR.mkdir(exist_ok=True)\n",
        "\n",
        "RATIOS_PATH = DATA_DIR / \"financial_ratios_generated.csv\"\n",
        "COMPANIES_PATH = DATA_DIR / \"companies_cleaned.csv\"\n",
        "\n",
        "POSSIBLE_PEER_FILES = [\n",
        "    DATA_DIR / \"peer_groups_cleaned.csv\",\n",
        "    DATA_DIR / \"peer_groups.csv\",\n",
        "    DATA_DIR / \"peer_groups.xlsx\",\n",
        "    RAW_DIR / \"peer_groups.xlsx\",\n",
        "]\n",
        "\n",
        "OUTPUT_PATH = OUTPUT_DIR / \"peer_comparison.xlsx\"\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Fallback Peer Groups\n",
        "# Used only if peer_groups file is unavailable or unreadable\n",
        "# ---------------------------------------------------------\n",
        "FALLBACK_PEER_GROUPS = {\n",
        "    \"Private Banks\": {\n",
        "        \"members\": [\"HDFCBANK\", \"ICICIBANK\", \"AXISBANK\", \"KOTAKBANK\", \"INDUSINDBK\"],\n",
        "        \"benchmark\": \"HDFCBANK\",\n",
        "    },\n",
        "    \"Public Banks\": {\n",
        "        \"members\": [\"SBIN\", \"BANKBARODA\", \"CANBK\", \"PNB\"],\n",
        "        \"benchmark\": \"SBIN\",\n",
        "    },\n",
        "    \"IT Services\": {\n",
        "        \"members\": [\"TCS\", \"INFY\", \"HCLTECH\", \"TECHM\", \"LTIM\"],\n",
        "        \"benchmark\": \"TCS\",\n",
        "    },\n",
        "    \"Pharmaceuticals\": {\n",
        "        \"members\": [\"SUNPHARMA\", \"CIPLA\", \"DRREDDY\", \"DIVISLAB\", \"TORNTPHARM\"],\n",
        "        \"benchmark\": \"SUNPHARMA\",\n",
        "    },\n",
        "    \"Automobiles\": {\n",
        "        \"members\": [\"MARUTI\", \"TATAMOTORS\", \"M&M\", \"BAJAJ-AUTO\", \"EICHERMOT\", \"HEROMOTOCO\", \"TVSMOTOR\"],\n",
        "        \"benchmark\": \"MARUTI\",\n",
        "    },\n",
        "    \"Life Insurance\": {\n",
        "        \"members\": [\"LICI\", \"HDFCLIFE\", \"SBILIFE\", \"ICICIPRULI\"],\n",
        "        \"benchmark\": \"LICI\",\n",
        "    },\n",
        "    \"Oil & Gas\": {\n",
        "        \"members\": [\"RELIANCE\", \"ONGC\", \"BPCL\", \"IOC\", \"GAIL\"],\n",
        "        \"benchmark\": \"RELIANCE\",\n",
        "    },\n",
        "    \"Power & Utilities\": {\n",
        "        \"members\": [\"NTPC\", \"POWERGRID\", \"TATAPOWER\", \"ADANIPOWER\", \"NHPC\", \"JSWENERGY\", \"ADANIGREEN\"],\n",
        "        \"benchmark\": \"NTPC\",\n",
        "    },\n",
        "    \"Steel & Metals\": {\n",
        "        \"members\": [\"TATASTEEL\", \"JSWSTEEL\", \"JINDALSTEL\", \"HINDALCO\"],\n",
        "        \"benchmark\": \"TATASTEEL\",\n",
        "    },\n",
        "    \"FMCG\": {\n",
        "        \"members\": [\"HINDUNILVR\", \"ITC\", \"BRITANNIA\", \"DABUR\", \"NESTLEIND\", \"GODREJCP\", \"TATACONSUM\"],\n",
        "        \"benchmark\": \"HINDUNILVR\",\n",
        "    },\n",
        "    \"Consumer Finance\": {\n",
        "        \"members\": [\"BAJFINANCE\", \"CHOLAFIN\", \"SHRIRAMFIN\"],\n",
        "        \"benchmark\": \"BAJFINANCE\",\n",
        "    },\n",
        "}\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# 20 Peer Comparison Metrics\n",
        "# ---------------------------------------------------------\n",
        "METRICS = [\n",
        "    \"return_on_equity_pct\",\n",
        "    \"return_on_capital_employed_pct\",\n",
        "    \"return_on_assets_pct\",\n",
        "    \"net_profit_margin_pct\",\n",
        "    \"operating_profit_margin_pct\",\n",
        "    \"ebit_margin_pct\",\n",
        "    \"debt_to_equity\",\n",
        "    \"interest_coverage\",\n",
        "    \"asset_turnover\",\n",
        "    \"free_cash_flow_cr\",\n",
        "    \"fcf_margin_pct\",\n",
        "    \"cfo_to_pat\",\n",
        "    \"capex_to_sales_pct\",\n",
        "    \"earnings_per_share\",\n",
        "    \"book_value_per_share\",\n",
        "    \"revenue_cagr_5y_pct\",\n",
        "    \"pat_cagr_5y_pct\",\n",
        "    \"eps_cagr_5y_pct\",\n",
        "    \"pe_ratio\",\n",
        "    \"pb_ratio\",\n",
        "]\n",
        "\n",
        "LOWER_IS_BETTER = {\n",
        "    \"debt_to_equity\",\n",
        "    \"capex_to_sales_pct\",\n",
        "    \"pe_ratio\",\n",
        "    \"pb_ratio\",\n",
        "}\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Utility Functions\n",
        "# ---------------------------------------------------------\n",
        "def clean_ticker(value):\n",
        "    if pd.isna(value):\n",
        "        return None\n",
        "    return str(value).strip().upper()\n",
        "\n",
        "\n",
        "def safe_sheet_name(name):\n",
        "    name = re.sub(r\"[\\[\\]\\:\\*\\?\\/\\\\]\", \"-\", str(name))\n",
        "    return name[:31]\n",
        "\n",
        "\n",
        "def load_peer_groups():\n",
        "    for path in POSSIBLE_PEER_FILES:\n",
        "        if not path.exists():\n",
        "            continue\n",
        "\n",
        "        try:\n",
        "            if path.suffix.lower() == \".xlsx\":\n",
        "                peer_df = pd.read_excel(path)\n",
        "            else:\n",
        "                peer_df = pd.read_csv(path)\n",
        "\n",
        "            peer_df.columns = [c.strip().lower() for c in peer_df.columns]\n",
        "\n",
        "            # Case 1: one row per company\n",
        "            # Expected-ish columns: peer_group, company_id, benchmark / is_benchmark\n",
        "            if \"company_id\" in peer_df.columns:\n",
        "                group_col = None\n",
        "                for candidate in [\"peer_group\", \"peer_group_name\", \"group\", \"peer_group_name\"]:\n",
        "                    if candidate in peer_df.columns:\n",
        "                        group_col = candidate\n",
        "                        break\n",
        "\n",
        "                if group_col is None:\n",
        "                    continue\n",
        "\n",
        "                parsed = {}\n",
        "\n",
        "                for group_name, group_rows in peer_df.groupby(group_col):\n",
        "                    members = group_rows[\"company_id\"].apply(clean_ticker).dropna().tolist()\n",
        "\n",
        "                    benchmark = None\n",
        "\n",
        "                    if \"benchmark\" in group_rows.columns:\n",
        "                        b = group_rows[\"benchmark\"].dropna()\n",
        "                        if len(b) > 0:\n",
        "                            benchmark = clean_ticker(b.iloc[0])\n",
        "\n",
        "                    if benchmark is None and \"is_benchmark\" in group_rows.columns:\n",
        "                        bench_rows = group_rows[group_rows[\"is_benchmark\"].astype(str).str.lower().isin([\"true\", \"1\", \"yes\"])]\n",
        "                        if not bench_rows.empty:\n",
        "                            benchmark = clean_ticker(bench_rows.iloc[0][\"company_id\"])\n",
        "\n",
        "                    if benchmark is None and members:\n",
        "                        benchmark = members[0]\n",
        "\n",
        "                    parsed[str(group_name)] = {\n",
        "                        \"members\": members,\n",
        "                        \"benchmark\": benchmark,\n",
        "                    }\n",
        "\n",
        "                if parsed:\n",
        "                    return parsed\n",
        "\n",
        "            # Case 2: one row per peer group with members as comma-separated string\n",
        "            possible_group_cols = [\"peer_group\", \"peer_group_name\", \"group\"]\n",
        "            possible_member_cols = [\"members\", \"company_ids\", \"companies\"]\n",
        "\n",
        "            group_col = next((c for c in possible_group_cols if c in peer_df.columns), None)\n",
        "            member_col = next((c for c in possible_member_cols if c in peer_df.columns), None)\n",
        "\n",
        "            if group_col and member_col:\n",
        "                parsed = {}\n",
        "\n",
        "                for _, row in peer_df.iterrows():\n",
        "                    group_name = str(row[group_col])\n",
        "                    members = [\n",
        "                        clean_ticker(x)\n",
        "                        for x in str(row[member_col]).split(\",\")\n",
        "                        if clean_ticker(x)\n",
        "                    ]\n",
        "\n",
        "                    benchmark = None\n",
        "                    if \"benchmark\" in peer_df.columns:\n",
        "                        benchmark = clean_ticker(row.get(\"benchmark\"))\n",
        "\n",
        "                    if benchmark is None and members:\n",
        "                        benchmark = members[0]\n",
        "\n",
        "                    parsed[group_name] = {\n",
        "                        \"members\": members,\n",
        "                        \"benchmark\": benchmark,\n",
        "                    }\n",
        "\n",
        "                if parsed:\n",
        "                    return parsed\n",
        "\n",
        "        except Exception as e:\n",
        "            print(f\"Could not read peer file {path}: {e}\")\n",
        "\n",
        "    print(\"Using fallback peer groups.\")\n",
        "    return FALLBACK_PEER_GROUPS\n",
        "\n",
        "\n",
        "def add_company_names(df):\n",
        "    if not COMPANIES_PATH.exists():\n",
        "        df[\"company_name\"] = df[\"company_id\"]\n",
        "        return df\n",
        "\n",
        "    companies = pd.read_csv(COMPANIES_PATH)\n",
        "    companies.columns = [c.strip() for c in companies.columns]\n",
        "\n",
        "    if \"id\" not in companies.columns:\n",
        "        df[\"company_name\"] = df[\"company_id\"]\n",
        "        return df\n",
        "\n",
        "    companies[\"id\"] = companies[\"id\"].apply(clean_ticker)\n",
        "\n",
        "    if \"company_name\" not in companies.columns:\n",
        "        companies[\"company_name\"] = companies[\"id\"]\n",
        "\n",
        "    return df.merge(\n",
        "        companies[[\"id\", \"company_name\"]],\n",
        "        left_on=\"company_id\",\n",
        "        right_on=\"id\",\n",
        "        how=\"left\",\n",
        "    ).drop(columns=[\"id\"], errors=\"ignore\")\n",
        "\n",
        "\n",
        "def calculate_peer_percentiles(peer_df):\n",
        "    output = peer_df.copy()\n",
        "\n",
        "    for metric in METRICS:\n",
        "        if metric not in output.columns:\n",
        "            output[metric] = np.nan\n",
        "\n",
        "        numeric_values = pd.to_numeric(output[metric], errors=\"coerce\")\n",
        "\n",
        "        higher_is_better = metric not in LOWER_IS_BETTER\n",
        "\n",
        "        output[f\"{metric}_percentile\"] = (\n",
        "            numeric_values.rank(\n",
        "                pct=True,\n",
        "                ascending=higher_is_better\n",
        "            ) * 100\n",
        "        )\n",
        "\n",
        "    return output\n",
        "\n",
        "\n",
        "def apply_excel_formatting(path, sheet_names, benchmark_map):\n",
        "    wb = load_workbook(path)\n",
        "\n",
        "    green_fill = PatternFill(\"solid\", fgColor=\"C6EFCE\")\n",
        "    yellow_fill = PatternFill(\"solid\", fgColor=\"FFF2CC\")\n",
        "    red_fill = PatternFill(\"solid\", fgColor=\"F4CCCC\")\n",
        "    benchmark_fill = PatternFill(\"solid\", fgColor=\"FCE4D6\")\n",
        "    header_fill = PatternFill(\"solid\", fgColor=\"1F4E78\")\n",
        "    median_fill = PatternFill(\"solid\", fgColor=\"D9EAF7\")\n",
        "\n",
        "    white_font = Font(color=\"FFFFFF\", bold=True)\n",
        "    bold_font = Font(bold=True)\n",
        "    thin_border = Border(\n",
        "        left=Side(style=\"thin\", color=\"D9E2F3\"),\n",
        "        right=Side(style=\"thin\", color=\"D9E2F3\"),\n",
        "        top=Side(style=\"thin\", color=\"D9E2F3\"),\n",
        "        bottom=Side(style=\"thin\", color=\"D9E2F3\"),\n",
        "    )\n",
        "\n",
        "    for sheet_name in sheet_names:\n",
        "        ws = wb[sheet_name]\n",
        "\n",
        "        max_row = ws.max_row\n",
        "        max_col = ws.max_column\n",
        "\n",
        "        # Header format\n",
        "        for cell in ws[1]:\n",
        "            cell.fill = header_fill\n",
        "            cell.font = white_font\n",
        "            cell.alignment = Alignment(horizontal=\"center\", vertical=\"center\", wrap_text=True)\n",
        "            cell.border = thin_border\n",
        "\n",
        "        # General formatting\n",
        "        for row in ws.iter_rows(min_row=2, max_row=max_row, max_col=max_col):\n",
        "            for cell in row:\n",
        "                cell.border = thin_border\n",
        "                cell.alignment = Alignment(vertical=\"center\", wrap_text=True)\n",
        "\n",
        "        # Identify percentile columns\n",
        "        percentile_cols = []\n",
        "        for col_idx in range(1, max_col + 1):\n",
        "            header = ws.cell(row=1, column=col_idx).value\n",
        "            if header and str(header).endswith(\"_percentile\"):\n",
        "                percentile_cols.append(col_idx)\n",
        "\n",
        "        # Colour percentile cells\n",
        "        for row_idx in range(2, max_row):\n",
        "            for col_idx in percentile_cols:\n",
        "                cell = ws.cell(row=row_idx, column=col_idx)\n",
        "                value = cell.value\n",
        "\n",
        "                if isinstance(value, (int, float)):\n",
        "                    if value >= 75:\n",
        "                        cell.fill = green_fill\n",
        "                    elif value <= 25:\n",
        "                        cell.fill = red_fill\n",
        "                    else:\n",
        "                        cell.fill = yellow_fill\n",
        "\n",
        "                    cell.number_format = \"0.0\"\n",
        "\n",
        "        # Highlight benchmark company row\n",
        "        benchmark = benchmark_map.get(sheet_name)\n",
        "\n",
        "        if benchmark:\n",
        "            for row_idx in range(2, max_row):\n",
        "                company_id = ws.cell(row=row_idx, column=1).value\n",
        "\n",
        "                if str(company_id).strip().upper() == benchmark:\n",
        "                    for col_idx in range(1, max_col + 1):\n",
        "                        ws.cell(row=row_idx, column=col_idx).fill = benchmark_fill\n",
        "                        ws.cell(row=row_idx, column=col_idx).font = bold_font\n",
        "\n",
        "        # Median row format\n",
        "        for cell in ws[max_row]:\n",
        "            cell.fill = median_fill\n",
        "            cell.font = bold_font\n",
        "            cell.border = thin_border\n",
        "\n",
        "        # Freeze panes and filters\n",
        "        ws.freeze_panes = \"C2\"\n",
        "        ws.auto_filter.ref = ws.dimensions\n",
        "\n",
        "        # Column widths\n",
        "        ws.column_dimensions[\"A\"].width = 16\n",
        "        ws.column_dimensions[\"B\"].width = 36\n",
        "\n",
        "        for col_idx in range(3, max_col + 1):\n",
        "            ws.column_dimensions[get_column_letter(col_idx)].width = 18\n",
        "\n",
        "        ws.row_dimensions[1].height = 45\n",
        "\n",
        "    wb.save(path)\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# Main Report Generator\n",
        "# ---------------------------------------------------------\n",
        "def generate_peer_comparison_report():\n",
        "    if not RATIOS_PATH.exists():\n",
        "        raise FileNotFoundError(\n",
        "            f\"Missing required file: {RATIOS_PATH}. \"\n",
        "            \"Run Ratio Engine first.\"\n",
        "        )\n",
        "\n",
        "    ratios = pd.read_csv(RATIOS_PATH)\n",
        "    ratios[\"company_id\"] = ratios[\"company_id\"].apply(clean_ticker)\n",
        "    ratios[\"fiscal_year\"] = pd.to_numeric(ratios[\"fiscal_year\"], errors=\"coerce\")\n",
        "\n",
        "    latest = (\n",
        "        ratios\n",
        "        .dropna(subset=[\"fiscal_year\"])\n",
        "        .sort_values([\"company_id\", \"fiscal_year\"])\n",
        "        .groupby(\"company_id\")\n",
        "        .tail(1)\n",
        "        .reset_index(drop=True)\n",
        "    )\n",
        "\n",
        "    latest = add_company_names(latest)\n",
        "\n",
        "    peer_groups = load_peer_groups()\n",
        "\n",
        "    benchmark_map = {}\n",
        "    sheet_names = []\n",
        "\n",
        "    with pd.ExcelWriter(OUTPUT_PATH, engine=\"openpyxl\") as writer:\n",
        "        for peer_group_name, config in peer_groups.items():\n",
        "            members = [clean_ticker(x) for x in config[\"members\"]]\n",
        "            benchmark = clean_ticker(config.get(\"benchmark\"))\n",
        "\n",
        "            peer_df = latest[latest[\"company_id\"].isin(members)].copy()\n",
        "\n",
        "            if peer_df.empty:\n",
        "                continue\n",
        "\n",
        "            peer_df = calculate_peer_percentiles(peer_df)\n",
        "\n",
        "            peer_df[\"is_benchmark\"] = peer_df[\"company_id\"].eq(benchmark)\n",
        "\n",
        "            metric_cols = METRICS\n",
        "            percentile_cols = [f\"{m}_percentile\" for m in METRICS]\n",
        "\n",
        "            report_cols = (\n",
        "                [\"company_id\", \"company_name\"]\n",
        "                + metric_cols\n",
        "                + percentile_cols\n",
        "            )\n",
        "\n",
        "            report_cols = [c for c in report_cols if c in peer_df.columns]\n",
        "\n",
        "            report_df = peer_df[report_cols].copy()\n",
        "\n",
        "            # Sort by benchmark first, then ROE percentile\n",
        "            sort_col = \"return_on_equity_pct_percentile\"\n",
        "            if sort_col in peer_df.columns:\n",
        "                order_df = peer_df[[\"company_id\", \"is_benchmark\", sort_col]].copy()\n",
        "                order_df = order_df.sort_values(\n",
        "                    [\"is_benchmark\", sort_col],\n",
        "                    ascending=[False, False]\n",
        "                )\n",
        "                report_df = report_df.set_index(\"company_id\").loc[order_df[\"company_id\"]].reset_index()\n",
        "\n",
        "            # Add median row\n",
        "            median_row = {col: \"\" for col in report_df.columns}\n",
        "            median_row[\"company_id\"] = \"MEDIAN\"\n",
        "            median_row[\"company_name\"] = \"Peer Group Median\"\n",
        "\n",
        "            for metric in metric_cols:\n",
        "                if metric in report_df.columns:\n",
        "                    median_row[metric] = pd.to_numeric(report_df[metric], errors=\"coerce\").median()\n",
        "\n",
        "            report_df = pd.concat(\n",
        "                [report_df, pd.DataFrame([median_row])],\n",
        "                ignore_index=True\n",
        "            )\n",
        "\n",
        "            sheet_name = safe_sheet_name(peer_group_name)\n",
        "            benchmark_map[sheet_name] = benchmark\n",
        "            sheet_names.append(sheet_name)\n",
        "\n",
        "            report_df.to_excel(writer, sheet_name=sheet_name, index=False)\n",
        "\n",
        "    apply_excel_formatting(OUTPUT_PATH, sheet_names, benchmark_map)\n",
        "\n",
        "    print(\"Peer Comparison Excel Report generated successfully!\")\n",
        "    print(f\"Saved to: {OUTPUT_PATH}\")\n",
        "    print(f\"Sheets created: {len(sheet_names)}\")\n",
        "\n",
        "    return OUTPUT_PATH\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    generate_peer_comparison_report()"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "K_vw6fxxXIy9"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}